package test.Day07ATest;

import org.junit.Test;
import software.aoc.day07.Laboratories;
import test.ReadTestFile;

import static org.assertj.core.api.Assertions.assertThat;

public class LaboratoriesTest {
    @Test
    public void given_multiple_test_check_result() {
        assertThat(Laboratories.executeA("""
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............
                """.split("\n"))).isEqualTo(21);
    }

    @Test
    public void given_aoc_puzzle_check_result() {
        assertThat(Laboratories.executeA(ReadTestFile.using("day07/input.txt")))
                .isEqualTo(1609);
    }
}
