package test.Day07BTest;

import org.junit.Test;
import software.aoc.day07.b.Laboratories;
import test.ReadTestFile;

import static org.assertj.core.api.Assertions.assertThat;

public class LaboratoriesTest {
    @Test
    public void given_multiple_test_check_result() {
        assertThat(Laboratories.execute("""
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............
                """.split("\n"))).isEqualTo(40L);
    }

    @Test
    public void given_aoc_puzzle_check_result() {
        assertThat(Laboratories.execute(ReadTestFile.using("day07/input.txt")))
                .isEqualTo(12472142047197L);
    }
}
